# Generated by Django 4.0.5 on 2024-06-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitprofiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Django',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'django',
            },
        ),
    ]
