# Generated by Django 4.0.5 on 2024-06-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitprofiler', '0002_django'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Django',
            new_name='Neon',
        ),
        migrations.AlterModelTable(
            name='neon',
            table=None,
        ),
    ]
